dependency_overrides:
  adaptive_number:
    path: ./dependencies/adaptive_number
  dots_indicator:
    path: ./dependencies/dots_indicator
  ed25519_edwards:
    path: ./dependencies/ed25519_edwards
  hashlib:
    path: ./dependencies/hashlib
  hashlib_codecs:
    path: ./dependencies/hashlib_codecs
  introduction_screen:
    path: ./dependencies/introduction_screen
  libsignal_protocol_dart:
    path: ./dependencies/libsignal_protocol_dart
  lottie:
    path: ./dependencies/lottie
  mutex:
    path: ./dependencies/mutex
  optional:
    path: ./dependencies/optional
  photo_view:
    path: ./dependencies/photo_view
  pointycastle:
    path: ./dependencies/pointycastle
  qr:
    path: ./dependencies/qr
  qr_flutter:
    path: ./dependencies/qr_flutter
  x25519:
    path: ./dependencies/x25519
