name: libsignal_protocol_dart
description: Signal Protocol libray for Dart native and Flutter, pure Dart implementation of the the Signal Protocol
version: 0.7.4
repository: https://github.com/MixinNetwork/libsignal_protocol_dart
topics:
 - crypto

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  adaptive_number: ^1.0.0
  collection: ^1.19.0
  convert: ^3.1.2
  crypto: ^3.0.6
  ed25519_edwards: ^0.3.1
  fixnum: ^1.1.1
  meta: ^1.16.0
  optional: ^6.1.0+1
  pointycastle: ^4.0.0
  protobuf: ^4.0.0
  x25519: ^0.1.1


dev_dependencies:
  test: ^1.25.8
  very_good_analysis: ^8.0.0
